---
# Installation de epel-release
- name: Install epel-release
  package:
    name: epel-release
    state: present

# Installation de haproxy,
# qui permet de rediriger le flux des requêtes sur app1 et app2
- name: Install haproxy
  package:
    name: haproxy
    state: present

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: false

- name: Set HAProxy version.
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: Disabling security enforced linux
  selinux:
    state: disabled

- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

# Démarre le service au lancement
- name: Ensure HAProxy is started and enabled on boot
  service:
    name: haproxy
    state: started
    enabled: yes