---
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

# Pour lancer le programme python sans Docker
# Installation de epel-release
- name: Install epel-release
  package:
    name: epel-release
    state: present

# Installation de Python 3.6
- name: Install python3 repository
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install python3.6 packages.
  yum:
    update_cache: True
    name:
      - python36u
      - python36u-libs
      - python36u-devel
      - python36u-pip
      - python36u-setuptools

- name: Install gcc compilator since it is required to install some of pip dependencies.
  yum:
    name: gcc

- name: Upgrade pip.
  command: pip3.6 install --upgrade pip

# Créer un répertoire pour l'application
- name: Créer répertoire app
  file:
    path: /app
    state: directory

# Copier l'application de Boris dans le répertoire
# puis l'extraire
- name: Copier le .tar de l'application puis l'extraire
  unarchive:
    src: data-engineering.tar
    dest: /app/

# Installe les outils pythons
- name: Install setuptools
  yum:
    name: python-setuptools
    update_cache: yes
    state: latest

# Installation de tous les modules/dépendances python utilisés par l'app de Boris
- name: Installation des dépendances python
  pip:
    executable: /bin/pip3.6
    requirements: /app/data-engineering/requirements.txt
#  command: pip3 install -r /data-engineering/requirements.txt

# Copy le fichier systemd à l'endroit approprié
- name: Copy local service config file to the target
  copy:
    src: app.service
    dest: /etc/systemd/system/



#- name: set Environment variables
#  environment:
#    ELASTICSEARCH_URL: "http://192.168.201.14:9200"
#    MONGODB_URI: "mongodb://192.168.201.13:27017"

#- name: set ELASTICSEARCH_URL
#  command: export ELASTICSEARCH_URL="http://192.168.201.14:9200"
#
#- name: set MONGODB_URI
#  command: export MONGODB_URI="mongodb://192.168.201.13:27017"



# Redémarrage
- name: Reload services
  command: systemctl daemon-reload

# Démarre le service au lancement
- name: Start app.service
  service:
    name: app.service
    enabled: yes
    state: started
